site_name: SUQ.py
site_url: https://AaltoML.github.io/SUQ # change this

repo_url: https://github.com/AaltoML/SUQ
repo_name: AaltoML/SUQ

theme: 
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github  # optional, for GitHub icon

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: false
            show_root_members: true
            show_root_toc_entry: false
            heading_level: 3
            group_by_category: true
            show_category_heading: true
            members_order: source

nav:
  - Home: index.md
  - API Reference: reference.md

